name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Run a lightweight trusted workflow for PRs from forks. This uses pull_request_target
  # which runs in the context of the base repository; to safely test the fork's code we
  # explicitly checkout the head of the PR. Be cautious with secrets — this workflow does
  # not expose secrets to untrusted code.
  pull_request_target:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * *' # nightly at 00:00 UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 17, 21 ]

    steps:
      - name: Checkout PR head (for pull_request_target)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout source
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ${{ runner.home }}/.m2/repository
          key: ${{ runner.os }}-m2-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-${{ matrix.java }}-

      - name: Build and run tests
        run: mvn -B test

      - name: Upload test reports (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.os }}-java${{ matrix.java }}
          path: target/surefire-reports/**/*.xml

      - name: Publish JUnit test reports to Checks
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit tests
          path: target/surefire-reports/**/*.xml
          reporter: junit
          # do not fail the job if the reporter fails
          fail-on-error: false

      - name: Generate HTML surefire report
        if: always()
        run: mvn -B surefire-report:report

      - name: Upload HTML test report (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report-${{ matrix.os }}-java${{ matrix.java }}
          path: target/site/**

